export enum Colour {
    Gray = "gray",
    Yellow = "yellow",
    Orange = "orange",
    Maroon = "maroon",
    Red = "red",
    Purple = "purple",
    Fuchsia = "fuchsia",
    Pink = "pink",
    Green = "green",
    Lime = "lime",
    Olive = "olive",
    Navy = "navy",
    Blue = "blue",
    Teal = "teal",
    Aqua = "aqua",
}
